version: '3.8'
services:
  pbmgr-gateway:
    build:
      context:
        .
      dockerfile: Dockerfile
    ports:
      - "8080:8088"
    networks:
       - db
    environment:
      GATEWAY_ADMIN_PASSWORD: password
      IGNITION_EDITION: full
      TZ: "America/New_York"
      IGNITION_STARTUP_DELAY: 180
    restart: unless-stopped
  pbmgr-db:
    image: mariadb:10.5
    ports:
      - "3307:3306"
    networks:
       - db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pbmgrdb
      MYSQL_USER: ignition
      MYSQL_PASSWORD: password
      TZ: "America/New_York"
    restart: unless-stopped
networks:
  db:
